name: Playwright Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CI: true
    CURRENCY_API_KEY: ${{ secrets.CURRENCY_API_KEY }}
    NEXT_PUBLIC_ENV: ${{ secrets.NEXT_PUBLIC_ENV }}
    POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
    PRINTIFY_API_TOKEN: ${{ secrets.PRINTIFY_API_TOKEN }}
    SHOP_ID: ${{ secrets.SHOP_ID }}

jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11
                  cache: "npm"

            - name: Install dependencies
              run: npm install -D
            - name: Install Playwright Browsers
              run: npm run e2e:install
            - name: Run Playwright tests
              run: npm run e2e:headless
